wormhole-foundation/native-token-transfers

- src/EndpointAndManager.sol
- src/EndpointManager.sol
- src/EndpointManagerStandalone.sol
- src/WormholeEndpoint.sol
- src/WormholeEndpointAndManager.sol
- src/WormholeEndpointStandalone.sol
- src/interfaces/IEndpointManager.sol
- src/libraries/EndpointStructs.sol
- test/EndpointManager.t.sol
Added tests for the `EndpointManager` against a dummy endpoint that just blindly forwards messages. 
We should factor out some of the tests so they can run against the standalone endpoint&manager contract too. Specifically, the endpoint&manager currently implements no replay protection and assumes that the endpoint does it, which I think is not right. For now I've left a TODO about it.
The tests also don't cover the case where quorum is reached and the message needs to be handled, because doing so would require setting up a token and other stuff for the business logic. I also left a TODO about this in the tests file (specifically that we should separate the business logic from the endpoint manager so the two can be tested separately & the contracts are more reusable that way too).
NOTE: I …
> add tests for EndpointManager

- src/Endpoint.sol
- src/EndpointAndManager.sol
- src/EndpointManager.sol
- src/EndpointManagerStandalone.sol
- src/EndpointStandalone.sol
- src/interfaces/IEndpointManagerStandalone.sol
- src/libraries/EndpointStructs.sol
- test/EndpointManager.t.sol
This makes `_executeMsg` perform replay protection, so that the different configurations of endpoints and manager don't have to independently reimplement this logic.
Also moved the struct util functions into a library, so the commits are best view separately
> Improve standalone arch

- src/Manager.sol
- src/interfaces/IManager.sol
- src/interfaces/IManagerEvents.sol
- test/Manager.t.sol
Closes https://github.com/wormhole-foundation/example-native-token-transfers/issues/42
Refactor inbound queue to key by source chain ID and manager message sequence.
> Refactor Inbound Queue Keying

- src/Manager.sol
- src/interfaces/IManager.sol
Use message sequence for outbound queue sequence and remove separate outbound sequence storage
> Outbound Queue -- use `ManagerMessage.sequence` instead of Outbound Queue Sequence

- src/Endpoint.sol
- src/EndpointAndManager.sol
- src/EndpointStandalone.sol
- src/Manager.sol
- src/WormholeEndpoint.sol
- src/WormholeEndpointAndManager.sol
- src/WormholeEndpointStandalone.sol
- src/interfaces/IEndpointStandalone.sol
- src/interfaces/IWormholeEndpoint.sol
- src/libraries/EndpointStructs.sol
Fix Wormhole standard relaying integration to properly receive messages and flexibly adapt to new evm chains.
This PR:
1. Uses Wormhole standard relaying when the target chain is EVM and supported by standard relaying.
2. Directly emits Wormhole messages via the core bridge when the conditions for (1) are not met.
A couple important things to note about the integration:
1. This change does not implement the case to handle a caller requesting for a transfer to not be emitted via Standard Relaying even if the target chain is EVM + relaying-supported. I'm playing around with local changes on how exactly to implement this, it requires some new structs and interface changes.
2. I've disallowed relayer deliveries with additionalMessages populated, since this contract never expects to receive a …
> Fix Wormhole Standard Relaying Integration

- src/Endpoint.sol
- src/EndpointAndManager.sol
- src/EndpointRegistry.sol
- src/EndpointStandalone.sol
- src/Manager.sol
- src/ManagerStandalone.sol
- src/WormholeEndpoint.sol
- src/WormholeEndpointAndManager.sol
- src/WormholeEndpointStandalone.sol
- src/interfaces/IEndpointStandalone.sol
- src/interfaces/IEndpointToken.sol
- src/interfaces/IManager.sol
- src/interfaces/IManagerEvents.sol
- src/interfaces/IManagerStandalone.sol
- src/interfaces/IWormholeEndpoint.sol
- src/libraries/EndpointHelpers.sol
- src/libraries/EndpointStructs.sol
- src/libraries/Implementation.sol
- src/wormhole/Governance.sol
- test/Manager.t.sol
- test/libraries/Implementation.t.sol
- test/libraries/Utils.sol
- test/wormhole/Governance.t.sol
Closes https://github.com/wormhole-foundation/example-native-token-transfers/issues/38
> Narrow compiler range to 0.8.x

- test/EndpointStructs.t.sol
- test/Manager.t.sol
This makes it a bit easier to keep track of the wire format changes as they will now be visible through changes to this test. Then other implementations (e.g. solana) can just make sure to always successfully parse this encoded payload.
> Add wire format tests

- src/Manager.sol
- src/NttNormalizer.sol
- src/libraries/NormalizedAmount.sol
- src/libraries/RateLimiter.sol
- test/Manager.t.sol
- Shift decimals to match the native token decimals when receiving an NTT transfer.
- Use `NttNormalizer` wrapper lib to enforce all NTT-related normalize/denormalize operations always use the proper decimals.
> Add NttNormalizer abstract contract

- .github/workflows/solana.yml
- solana/Cargo.toml
- solana/programs/example-native-token-transfers/Cargo.toml
- solana/programs/wormhole-governance/Cargo.toml
previously, the wormhole-anchor-sdk just built against the mainnet addresses
> solana: specify target network

- evm/src/EndpointRegistry.sol
- evm/src/Manager.sol
- evm/src/NttNormalizer.sol
- evm/src/WormholeEndpoint.sol
- evm/src/interfaces/IManager.sol
- evm/src/interfaces/IRateLimiter.sol
- evm/src/libraries/EndpointHelpers.sol
- evm/src/libraries/Implementation.sol
- evm/src/libraries/PausableOwnable.sol
- evm/src/libraries/PausableUpgradeable.sol
- evm/src/libraries/RateLimiter.sol
- evm/src/libraries/external/OwnableUpgradeable.sol
- evm/test/Manager.t.sol
- evm/test/RateLimit.t.sol
- evm/test/Upgrades.t.sol
- evm/test/mocks/MockEndpoints.sol
- evm/test/mocks/MockManager.sol
This set of commits gives us just over 2kB of breathing room without touching the invariants. Have a look at the commit messages to see how much each set of changes saves us.
> evm: Reduce contract size of Manager

- evm/src/WormholeEndpoint.sol
- evm/test/IntegrationStandalone.t.sol
Currently the `transfer(uint256 amount, uint16 recipientChain, bytes32 recipient)` variant always fails with the WH endpoint since the instruction payload is 0 bytes long by default when it isn't provided. This updates the parser to exit early and default to false if no instructions are provided.
> evm: Fix empty instructions for WH endpoint

- evm/src/NttManager.sol
- evm/src/WormholeTransceiver.sol
- evm/src/interfaces/INttManagerEvents.sol
- evm/src/interfaces/IWormholeTransceiver.sol
> add useful event info

- evm/src/NttManager/TransceiverRegistry.sol
> fix: remove duplicate event emissions

- evm/src/NttManager/NttManagerState.sol
- evm/src/libraries/RateLimiter.sol
- evm/src/libraries/TrimmedAmount.sol
Previously, the rate limits were not initialised, which was masked by the graceful handling of the trimmed arithmetic operations when they encountered zero values. That handling was wrong, as we should handle the zero case exactly where it's expected: the `setLimit` function (the old values will be zero on init).
Also added outbound limit initialisation to the manager initialiser, and inbound limit initialisation to peer registration. We could consider thaking the inbound limit as an argument when registering a peer instead of the current behaviour which is to set it to the max limit. That's what the solana implementation does.
> evm: guarantee that rate limits are initialised

- evm/src/NttManager/NttManagerState.sol
- evm/test/NttManager.t.sol
- evm/test/RateLimit.t.sol
There's a bug in the function ``transceiverAttestedToMessage()`` for indexes greater than 0.
Original code - ``_getMessageAttestationsStorage()[digest].attestedTransceivers & uint64(1 << index) == 1;`` 
* The call at the beginning is getting a bitmap of attested transceivers. So, 7 (b111) would be 3 accepted transceivers. 
* Next, we are computing the index to compare on the bitmap with transceiver index. So, if we want check the second index then 1 << 1 would work to produce 2 or the middle bit out of the 3 in the example. 
* Finally, we're comparing this with 1, which is where the bug is at. This is ONLY true if we're checking the first index. For instance, if we're checking the second index (value of 1) then we'd do ``7 & (1 << 1) == 1`` or ``7 & 2 == 1`` which is ``2 == 1`` . So, the …
> Fix incorrect bitwise comparison

- evm/src/NttManager/TransceiverRegistry.sol
- evm/test/NttManager.t.sol
Previously we'd revert if trying to re-enable a transceiver that's already been registered when we hit the 64 registered transceiver cap. This change allows the transceiver to be re-enabled.
> evm: Always allow re-enabling a previously registered transceiver

- evm/src/NttManager/NttManager.sol
- evm/src/libraries/RateLimiter.sol
- evm/src/libraries/TransceiverStructs.sol
- evm/src/libraries/TrimmedAmount.sol
- evm/test/NttManager.t.sol
- evm/test/RateLimit.t.sol
- evm/test/TransceiverStructs.t.sol
- evm/test/TrimmedAmount.t.sol
- evm/test/libraries/NttManagerHelpers.sol
- evm/test/libraries/TransceiverHelpers.sol
Fixes #231. 
This PR modifies the current TrimmedAmount struct to a bit-packed representation of a token amount and its decimals.   
```
/// @dev 64 bytes: [0 - 64] amount
/// @dev 8 bytes: [64 - 72] decimals
type TrimmedAmount is uint72; 
```  
This representation is advantageous for two reasons: (1) Less runtime overhead (since structs point to memory, calldata, or storage). Using a user-defined value type allows the trimmed amounts to be stack-allocated; (2) the ability to overload the traditional arithmetic binary operators (+/-/*, etc..) for operations on trimmed amounts.
The use of `uint72` instead of larger unsigned integer types ensures that extra words are not allocated downstream for other data types that contain `TrimmedAmounts` (e.g. `RateLimitParams`)
> evm: modify trimmed amt struct -> uint72

- evm/src/NttManager/NttManager.sol
- evm/src/NttManager/NttManagerState.sol
- evm/src/mocks/DummyToken.sol
- evm/test/NttManager.t.sol
Previously we cached the token decimals to save gas. However if the token linked to an NttManager was an upgradeable contract and the number of decimals of the token changed, then we'd be working with an out-of-date decimal amount and minting/unlocking orders of magnitude too many/few tokens.
This change forces us to always fetch the actual token decimals from the token contract when needed. If the decimals of the token do change, then all transfers will fail due to the decimal check on the rate limiting logic (assuming rate limiting is enabled and until the rate limiting configuration is updated). In the case where rate limiting is disabled, the impact is that dust is lost when trimming from the source chain until the peer configuration is updated.
The failure case is recoverable with a …
> evm: Always fetch token decimals rather than caching

- solana/Cargo.toml
- solana/modules/ntt-messages/Cargo.toml
- solana/modules/ntt-messages/src/trimmed_amount.rs
- solana/programs/example-native-token-transfers/Cargo.toml
- solana/programs/example-native-token-transfers/src/instructions/transfer.rs
- solana/programs/example-native-token-transfers/src/queue/rate_limit.rs
- solana/programs/ntt-quoter/Cargo.toml
- solana/programs/ntt-quoter/src/processor/request_relay.rs
- solana/programs/wormhole-governance/Cargo.toml
Adds deny directives to the project's clippy configuration so that risky programming patterns are forbidden.
Adds a variety of clippy lints to enforce safe programming patterns 
Adds allow annotations for known-safe examples and explanations as to why they're OK
Modifies some minor violations in the codebase
> solana: Configure additional security-relevant clippy lints

- evm/test/NttManager.t.sol
- evm/test/RateLimit.t.sol
- evm/test/TrimmedAmount.t.sol
> evm: add fuzz tests

- solana/programs/example-native-token-transfers/src/error.rs
- solana/programs/example-native-token-transfers/src/instructions/transfer.rs
token2022 supports tokens with fees. The `transfer_checked_with_fee` function that's referenced in many places in the toke2022 documentation doesn't seem to actually exist in the sdk (or the token2022 program), and there are no helpers to perform fee calculation, so for now I've just done the defensive step of enforcing no fees by checking the transferred amount.
We could support this case once there's appropriate sdk support
> solana: enforce no fees have been charged

- evm/src/NttManager/ManagerBase.sol
- evm/src/Transceiver/WormholeTransceiver/WormholeTransceiver.sol
- evm/src/interfaces/IManagerBase.sol
- evm/test/Upgrades.t.sol
We now query the wormhole fee to ensure NTT deployments with the Wormhole transceiver don't need to make an upgrade if the fee is changed to be non-zero.
I've also updated the public view for `quoteDeliveryPrice` to make it more useful since the caller now only has to pass in the transceiver instructions, not the list of enabled transceivers as well.
> evm: Query wormhole fee and improve quote view

- solana/README.md
If the toolchain is not configured properly on the local machine, the code will fail to build and run and will emit only very cryptic errors.
> solana: Add build prerequisites to README

- evm/README.md
- evm/cfg/WormholeNttConfig.json.sample
- evm/env/.env.sample
- evm/script/DeployWormholeNtt.s.sol
- evm/script/UpgradeWormholeTransceiver.s.sol
- evm/script/helpers/ParseNttConfig.sol
This PR fixes the deployment/upgrade scripts. The outbound limit should be set as an untrimmed value.
> evm: fix deployment script

- evm/src/NttManager/ManagerBase.sol
- evm/test/NttManager.t.sol
Note that this change prevents an admin from disabling all the transceivers from an NTT manager...there has to be at least 1 enabled transceiver at all times when `numRegisteredTransceivers > 0`.
> evm: Check threshold invariants when adding/removing transceivers

- evm/src/NttManager/NttManager.sol
- evm/src/Transceiver/WormholeTransceiver/WormholeTransceiverState.sol
- evm/src/interfaces/INttManager.sol
- evm/src/interfaces/IWormholeTransceiverState.sol
- evm/src/libraries/Implementation.sol
We don't query the wormhole message fee to save gas. The call will revert if the fee amount is not exact.
> evm: Make initialiser payable to allow WH transceiver registration

- evm/src/NttManager/NttManager.sol
- evm/test/IntegrationStandalone.t.sol
- evm/test/NttManager.t.sol
There was a very unlikely scenario whereby a source chain could fork, wormhole supports this forked chain, and the admin of the forked NTT manager updates the chain id and supports this new peer. Any queued transfers could then be played twice, once from the original chain, and once from the forked chain. You'd double your money on the destination chain.
This change adds a fork check on all the key entry and exit points:
- When queuing a transfer
- When sending both a queued and non-queued transfer
- When releasing funds on execution of a message
- When trying to cancel a queued outbound transfer
> evm: Check forks on all entrypoints

- evm/test/IntegrationManual.t.sol
> evm: Change RPC node to improve test stability

- evm/test/IntegrationManual.t.sol
- evm/test/IntegrationRelayer.t.sol
Results of running `forge fmt` in the evm directory
Note: running `forge fmt` with the version I had installed didn't change anything, I had to `foundryup` for it to provide the same changes as [CI which uses](https://github.com/wormhole-foundation/example-native-token-transfers/blob/main/.github/workflows/evm.yml#L26-L28) `nightly`
> Evm: format with nightly forge

- .github/workflows/solana.yml
- solana/Anchor.toml
- solana/Cargo.lock
- solana/Cargo.toml
- solana/Dockerfile
- solana/Makefile
- solana/programs/example-native-token-transfers/Cargo.toml
- solana/programs/example-native-token-transfers/src/instructions/initialize.rs
- solana/programs/example-native-token-transfers/tests/common/setup.rs
- solana/scripts/patch-idl
- solana/scripts/run-ts-tests
This PR upgrades the solana sdk version from 1.17.2 to 1.18.10.
The main reason for the upgrade is in preparation for supporting token22 tokens with transfer hooks, as the new version includes several bug fixes in the on-chain CPI helper functions.
The upgrade is smooth for the most part, two minor changes were necessary:
1. Heap allocated the mint account in `initialize`. This was necessary because I was getting a stack overflow when testing a token22 mint with extensions (and the mint account's size is dynamically allocated depending on which extensions are used). As an aside, we should consider heap-allocating the mint account in other instructions too for the same reason.
2. The `ProcessInstructionWithContext` type no longer resolved in the test setup module. The argument it was …
> solana: upgrade to solana version 1.18.10

- solana/programs/example-native-token-transfers/tests/governance.rs
- solana/programs/wormhole-governance/src/error.rs
- solana/programs/wormhole-governance/src/instructions/governance.rs
this matches the EVM implementation.
The primary motivation for having this field is that it allows transferring ownership to a different version of the governance program (since the program itself is not upgradeable), and ensuring that old message still cannot be replayed (since the governance program maintains its own replay protection)
> solana: put governance program in governance payload

- evm/test/wormhole/Governance.t.sol
- solana/Cargo.lock
- solana/programs/wormhole-governance/Cargo.toml
- solana/programs/wormhole-governance/src/instructions/governance.rs
This PR fixes the width of the governance action (from the inferred usize to u8). Also, extracted the body serialiser code for governance packets, as that will be needed to generate actual governance proposals.
> solana: fix governance action byte and add serde test from guardian

- solana/programs/example-native-token-transfers/src/instructions/initialize.rs
- solana/programs/example-native-token-transfers/src/instructions/release_inbound.rs
The associated token program instructions default to the legacy SPL token program. We pass the token_program as an argument to support token2022 tokens too.
> solana: pass token_program to ATA (support token22)

- .github/workflows/solana.yml
- solana/Makefile
- solana/idl/json/dummy_transfer_hook.json
- solana/idl/json/example_native_token_transfers.json
- solana/idl/json/ntt_quoter.json
- solana/idl/json/wormhole_governance.json
- solana/idl/ts/dummy_transfer_hook.ts
- solana/idl/ts/example_native_token_transfers.ts
- solana/idl/ts/ntt_quoter.ts
- solana/idl/ts/wormhole_governance.ts
- solana/ts/sdk/ntt.ts
- solana/ts/sdk/quoter.ts
Needed this for https://github.com/wormhole-foundation/example-native-token-transfers/pull/428.
I see that the IDL stuff is already checked in (under different versions). Are those usable from within the sdk functions? I was a little surprised to see that the idl is copied outside of the solana folder.
It would be nice to consolidate and only have to have a single copy, so I'm happy to rework this.
> solana: check in IDL

- evm/src/libraries/TrimmedAmount.sol
- evm/test/TrimmedAmount.t.sol
The code that tests operations on trimmed amounts previously made a
`vm.assume` call to enforce that the decimals of both amounts are the
same.
Since the decimal is an 8 bit value, the probability that
two (uniformly) randomly generated decimals are the same is 1/256,
meaning that the vast majority of test cases were discarded.
Now, we instead set the decimals of the first number to the decimals of
the second number. This does not change* the characteristics of the test
cases, as the amounts are sampled independently from the decimals.
*NOTE: this is only true under the assumption that the TrimmedAmount
type (which is backed by a uint72) is actually sampled from a uniform
distribution. This might not be the case depending on the fuzzer
implementation, as some fuzzers prefer certain edge …
> evm: make TrimmedAmount fuzz tests more efficient (fixes #431)

- evm/env/.env.sample
- evm/sh/deploy_wormhole_ntt.sh
- evm/sh/upgrade_ntt_manager.sh
- evm/sh/upgrade_wormhole_transceiver.sh
Found this useful when going through the NTT deployment for ethfi @nik-suri. Just adds contract verification to forge scripts that deploy new contracts.
> evm: adding contract verification to forge deploy scripts

- solana/ts/lib/ntt.ts
- solana/ts/sdk/ntt.ts
The fee returned from `quoteDeliveryPrice` is in lamports but the `createRequestRelayInstruction` expects it to be in Sol
> SDK: Fix the relay fee amount in Solana NTT

- solana/package.json
Temporary fix as entrypoint needs to be set to dist/cjs|esm/ts/ directory.
> Fix sdk-solana-ntt entry point

- evm/ts/package.json
- evm/ts/src/bindings.ts
- evm/ts/src/ntt.ts
- package-lock.json
- package.json
- sdk/definitions/package.json
- sdk/definitions/src/layouts/index.ts
- sdk/definitions/src/ntt.ts
- sdk/examples/package.json
- sdk/examples/src/consts.ts
- sdk/examples/src/route.ts
- sdk/route/package.json
- sdk/route/src/automatic.ts
- sdk/route/src/manual.ts
- sdk/route/src/types.ts
- solana/package.json
- solana/ts/lib/bindings.ts
- solana/ts/lib/ntt.ts
- solana/ts/sdk/ntt.ts
- Added a WormholeTransferStandardRelayer payload type needed to parse the VAA for an automatic transfer between EVM chains
- EVM: getIsExecuted should check if the transfer is inbound queued to determine if the transfer is completed
- Solana: getIsExecuted should check if the inboxItem is released
- Solana: getIsApproved should not swallow exception
- Solana: getInboundQueuedTransfer should return null if the transfer is not queued
- Bumped SDK dependencies needed for Connect
> Typescript SDK changes and bug fixes needed for Connect

- cli/src/index.ts
- evm/script/DeployWormholeNtt.s.sol
This works around and edge case when the token contract is compiled against a different EVM version than what the forge script is running in (london currently).
> cli: query token decimals outside of forge script

- solana/programs/example-native-token-transfers/tests/common/setup.rs
- solana/programs/example-native-token-transfers/tests/sdk/accounts.rs
- solana/programs/example-native-token-transfers/tests/sdk/instructions/initialize.rs
- solana/programs/example-native-token-transfers/tests/sdk/instructions/transfer.rs
- solana/programs/example-native-token-transfers/tests/transfer.rs
This PR adds:
- Test cases for locking and burning modes to handle tokens with transfer fee
- `*_with_token_program_id` helper methods to choose token program for the tests
> solana: Add Rust test cases to handle tokens with transfer fee

- .github/workflows/solana.yml
Disabling this fixes some seemingly unrelated linker errors. Not sure if this is the actual root cause.
> CI: disable rust toolchain cache

- solana/programs/example-native-token-transfers/src/instructions/transfer.rs
To support fee tokens, apart from first transferring and then asserting that there is no dust, we would also need to calculate the new amount to be burnt. This can be calculated as the amount _after_ paying the fees. This PR updates the comment to reflect that.
> solana: Update fee token comment to include required burn changes

- solana/Cargo.toml
This is currently enabled as a flag in the github CI workflow so this commit causes this to be reflected within the project itself
> solana: Deny rust clippy warnings in Cargo.toml

- solana/clippy.toml
These rules should help prevent linting noise. Unfortunately `allow-panic-in-tests` doesn't exist.
> solana: Clippy: allow unwrap/expect in tests

- .github/workflows/solana.yml
- solana/Cargo.toml
- solana/programs/example-native-token-transfers/src/bitmap.rs
- solana/programs/example-native-token-transfers/src/queue/rate_limit.rs
- solana/programs/wormhole-governance/src/instructions/governance.rs
Adds a [clippy rule](https://rust-lang.github.io/rust-clippy/master/index.html#/cast_possible_truncation) that blocks the inclusion of code that can result in truncation problems (i.e. denies `<T> as <U>` conversions where T has a greater capacity than U)
Adds linting directive to existing instances in the code and add comments about why they are safe
Also adds some unit test on the bitmap struct to make its edge-cases more legible.
> solana: Configure clippy to deny possible truncation

- sdk/examples/src/index.ts
the first tx hash may be the spending approval if from an evm chain
> examples: fetch vaa for last tx hash

- .github/workflows/solana.yml
- solana/Makefile
- solana/programs/example-native-token-transfers/src/instructions/admin.rs
- solana/programs/example-native-token-transfers/src/instructions/initialize.rs
- solana/programs/example-native-token-transfers/src/instructions/luts.rs
- solana/programs/example-native-token-transfers/src/instructions/release_inbound.rs
- solana/programs/example-native-token-transfers/src/instructions/transfer.rs
- solana/programs/example-native-token-transfers/src/transceivers/wormhole/instructions/broadcast_id.rs
- solana/programs/example-native-token-transfers/src/transceivers/wormhole/instructions/broadcast_peer.rs
- solana/programs/wormhole-governance/src/instructions/governance.rs
- solana/scripts/anchor-lint.sh
> solana: Add anchor linting

- solana/programs/example-native-token-transfers/src/bitmap.rs
- solana/programs/example-native-token-transfers/src/error.rs
- solana/programs/example-native-token-transfers/src/instructions/redeem.rs
- solana/programs/example-native-token-transfers/src/instructions/transfer.rs
- solana/ts/idl/2_0_0/json/example_native_token_transfers.json
- solana/ts/idl/2_0_0/json/wormhole_governance.json
- solana/ts/idl/2_0_0/ts/example_native_token_transfers.ts
- solana/ts/idl/2_0_0/ts/wormhole_governance.ts
> solana: Add no registered transceivers check

- solana/programs/example-native-token-transfers/src/instructions/admin.rs
- solana/programs/example-native-token-transfers/src/lib.rs
- solana/programs/example-native-token-transfers/tests/governance.rs
When reviewing, it's best to look at the differences between the new instruction and `transfer_ownership`. The changes:
1. immediately set the new owner
2. use `set_upgrade_authority` instead of `set_upgrade_authority_checked`
Reused the same account struct between the two. Technically the `upgrade_lock` account is redundant on this 1-step transfer code path, but it's a small price to pay for not having to duplicate the entire account struct.
> solana: add instruction to transfer ownership in one step

- .github/workflows/evm.yml
- evm/Makefile
Contract changes should not be made which would put the contract size over the Spurious Dragon limit. This check enforces that expectation.
Example failure https://github.com/wormhole-foundation/example-native-token-transfers/actions/runs/10908191583/job/30273582513?pr=518
Example success https://github.com/wormhole-foundation/example-native-token-transfers/actions/runs/10908415055/job/30274332155?pr=518
> ci: fail evm over size limit

- .gitignore
- README.md
- docs/NttManager.md
- docs/Transceiver.md
This PR explicitly documents the wire format spec implemented across the EVM, SVM, and TS code.
https://github.com/wormhole-foundation/example-native-token-transfers/blob/eeea26f6506e7b1a012851329636f098b5cbe4fc/evm/src/libraries/TransceiverStructs.sol#L41-L56
https://github.com/wormhole-foundation/example-native-token-transfers/blob/eeea26f6506e7b1a012851329636f098b5cbe4fc/evm/src/libraries/TransceiverStructs.sol#L37-L39
https://github.com/wormhole-foundation/example-native-token-transfers/blob/eeea26f6506e7b1a012851329636f098b5cbe4fc/evm/src/libraries/TransceiverStructs.sol#L90-L107
https://github.com/wormhole-foundation/example-native-token-transfers/blob/eeea26f6506e7b1a012851329636f098b5cbe4fc/evm/src/libraries/TransceiverStructs.sol#L152-L171 …
> docs: current wire formats

- solana/tests/anchor.test.ts
- solana/ts/sdk/ntt.ts
`getRecentBlockhash` is deprecated and being removed in solana-core 2.0 https://github.com/anza-xyz/agave/wiki/Agave-v2.0-Transition-Guide
> sdk: update deprecated solana web3.js methods

- evm/README.md
- evm/src/NttManager/NttManager.sol
- evm/src/NttManager/NttManagerNoRateLimiting.sol
- evm/src/interfaces/INttManager.sol
- evm/src/libraries/RateLimiter.sol
- evm/test/IntegrationWithoutRateLimiting.t.sol
- evm/test/NttManagerNoRateLimiting.t.sol
- evm/test/Upgrades.t.sol
- evm/test/mocks/MockNttManager.sol
This PR allows integrators to use NTT without rate limiting, in order to free up more space for adding their own custom features. If an integrator chooses to use `NttManagerNoRateLimiting`, they will have over 6K of head space for custom development, over using the existing `NttManager`.
> EVM: NttManagerNoRateLimiting implementation

- evm/README.md
- evm/src/NttManager/NttManager.sol
- evm/src/interfaces/INttManager.sol
- evm/src/libraries/TransceiverStructs.sol
- evm/test/IntegrationStandalone.t.sol
Before
```
| NttManager                            |   23,615 |        961 |
| NttManagerNoRateLimiting              |   18,169 |      6,407 |
```
After
```
| NttManager                            |   23,755 |        821 |
| NttManagerNoRateLimiting              |   18,403 |      6,173 |
```
> evm: TransferSent(bytes32), fixes #503

- evm/src/NttManager/NttManager.sol
- evm/test/mocks/MockNttManagerAdditionalPayload.sol
This PR updates the parameters for `_prepareNativeTokenTransfer` 
- remove `token`, as it is an immutable of `ManagerBase.sol` and always accessible.
- add `refundAddress` in case an integrator chooses to reference that in their additional payload.
> evm: update _prepareNativeTokenTransfer params

- cli/src/index.ts
- evm/ts/src/ntt.ts
- sdk/__tests__/utils.ts
- solana/Anchor.toml
- solana/scripts/anchor-lint.sh
- solana/tests/anchor.test.ts
- solana/ts/sdk/ntt.ts
* Allow `SolanaNtt` constructor to take in Wormhole transceiver address as either `emitterAccount` (if using baked-in transceiver) or the transceiver `programId` (if using standalone)
* Add test case to handle initialization using `emitterAccount`
* Update CLI and SDK tests to correctly pass in the `emitterAddress` as transceiver address
* Update `verifyAddresses` to return remote Wormhole transceiver address regardless of local case
This PR aims to fix the CI issues related to the SDK and CLI as a result of the changes introduced by #535.
> CI: Debug CI for multi-transceiver support

- cli/package.json
- evm/ts/package.json
- package-lock.json
- package.json
- sdk/definitions/package.json
- sdk/examples/package.json
- sdk/route/package.json
- solana/package.json
- Updates Wormhole SDK dependencies to `1.0.0`
- Moves them out of `dependencies` and into `peerDependencies` (since this is an SDK [plugin](https://blog.bitsrc.io/understanding-peer-dependencies-in-javascript-dbdb4ab5a7be))
> Update to wormhole SDK 1.0

- solana/ts/sdk/ntt.ts
getIsApproved() was returning true when the VAA was posted, causing track() to set the receipt state to DestinationInitiated prematurely. It should check if the inbox item is initialized instead.
Fixes an issue that caused calls to NttAutomaticRoute.complete() to return early and never actually complete the transfer in rare cases (receipt.DestinationInitiated === true and inbox item not created).
> solana sdk: Fix getIsApproved to check inbox item

- sdk/definitions/src/layouts/transfer.ts
The Layout type is not exported in newer versions of the Wormhole SDK, so we are removing its use now to avoid the issue in the future.
> sdk: use Layout instead of LayoutItem

- cli/install.sh
- cli/package.json
The `git ls-remote` command formats its output as follows:
```
fc0f34f97ecb0e9b0b21622cb1817700ed7f4a49	refs/tags/v1.0.0+cli
a1c11ef5958113b6a00b93967e8cef54c887a639	refs/tags/v1.0.1+cli
```
so when we sort it, it actually sorts the git hashes, and not the versions. So we rearrange the commands to first drop the commit hashes and then the sort (rather than doing it the other way around like before).
> cli: fix install/update latest version picker

- evm/src/Transceiver/WormholeTransceiver/WormholeTransceiver.sol
`WormholeTransceiver` takes `consistencyLevel` in the constructor, but doesn't pass it to `WormholeRelayer` in `_sendMessage` resulting in `FINALIZED` consistency level being used by default.
`IWormholeRelayer.sendPayloadToEvm` function call was replaced with `IWormholeRelayer.sendToEvm` to allow passing consistency level. The rest of parameters were filled from `WormholeRelayer` implementation.
I'm happy to add tests for the proposed changes, but there isn't any existing tests for the Transceivers
> evm: pass consistencyLevel to WormholeRelayer during send

- sdk/route/src/automatic.ts
Need to check if the route is actually available on the contract.
> sdk: automatic route is available fix

- Tiltfile
- evm/Dockerfile
- solana/Dockerfile
- solana/Dockerfile.test-validator
- solana/solana-devnet.yaml
This PR adds support for solana-test-validator within Docker / Tilt for M-series Macs. See also https://github.com/wormhole-foundation/wormhole/pull/4175 and https://github.com/wormhole-foundation/wormhole/pull/4181 which made this possible.
It also changes the `sed` line to one that works on Mac and Linux / WSL. To confirm that line still works in ci, I did a run with the guardian log level on `info` [here](https://github.com/wormhole-foundation/native-token-transfers/actions/runs/12204869868/job/34050904852?pr=563) where you can search for `8bf0b547c96edc5c1d512ca25c5c1d1812a180438a0046e511d1fb61561d5cdf` and the other emitters added to confirm they are being accounted (search for `gacct` guardian logs).
Bonus: this changes the result of `solana/Dockerfile` to only contain the required …
> tilt: solana-test-validator multi-platform support

- cli/src/index.ts
testing an alternate approach to #573. I think the test is simply failing because the deploy is using `confirmed` and the read is using `finalized` (or something like that). My hunch is that setting the deploy to `finalized` should incorporate the appropriate wait time.
> cli: use finalized commitment level for solana program deploy

- solana/programs/example-native-token-transfers/src/error.rs
- solana/programs/example-native-token-transfers/src/instructions/admin.rs
- solana/programs/example-native-token-transfers/src/lib.rs
- solana/programs/example-native-token-transfers/src/pending_token_authority.rs
- solana/ts/idl/3_0_0/json/example_native_token_transfers.json
- solana/ts/idl/3_0_0/ts/example_native_token_transfers.ts
- solana/ts/lib/ntt.ts
This PR adds:
* Two ways to transfer out mint authority like `transfer_ownership`:
* One step version: `set_token_authority_one_step_unchecked` ix
* Two step version: `set_token_authority` and `claim_token_authority` ix (and `revert_token_authority` to reset authority back to `token_authority`)
* `createSetTokenAuthorityInstruction` helper function in `NTT` namespace
* Update IDL
> solana: Allow transferring mint authority

- evm/test/TrimmedAmount.t.sol
With Foundry v1 release, some forge tests have been failing with this error. 
This PR fixes this by adding `/// forge-config: default.allow_internal_expect_revert = true` above the test function.
See https://book.getfoundry.sh/cheatcodes/expect-revert#description for reference:
> Selectively by using an inline configuration entry where it is DEEMED SAFE:
> Add `/// forge-config: default.allow_internal_expect_revert = true` above the test function.
> ci: Fix `call didn't revert at a lower depth than cheatcode call depth` forge error in EVM tests

- solana/programs/example-native-token-transfers/src/bitmap.rs
- solana/programs/example-native-token-transfers/src/error.rs
- solana/programs/example-native-token-transfers/src/instructions/admin/mod.rs
- solana/programs/example-native-token-transfers/src/instructions/initialize.rs
- solana/programs/example-native-token-transfers/src/lib.rs
- solana/programs/example-native-token-transfers/tests/admin.rs
- solana/programs/example-native-token-transfers/tests/sdk/instructions/admin.rs
- solana/ts/idl/3_0_0/json/example_native_token_transfers.json
- solana/ts/idl/3_0_0/ts/example_native_token_transfers.ts
- solana/ts/lib/ntt.ts
- solana/ts/sdk/ntt.ts
Currently there is no way to update the NTT manager `threshold` (# of transceivers that must attest to a transfer before it is accepted) - it defaults to 1 - or deregister a transceiver. With multi-transceiver support, having a way to manage transceivers and their threshold is essential.
This PR adds:
* `set_threshold` ix to update the threshold (`0 < threshold <= # of enabled transceivers`)
* `deregister_transceiver` ix to deregister (disable transceiver in enabled transceiver bitmap):
* Also decrements threshold (down to minimum 1) if # of enabled transceivers < threshold 
* Update `register_transceiver` ix to also act as re-enable:
* If `RegisteredTransceiver` account is init for the first time, assign new id
* Otherwise, reuse old id
* Rust tests to verify edge cases
* …
> solana: Add `set_threshold` ix

- solana/programs/example-native-token-transfers/src/instructions/admin/transfer_token_authority.rs
- solana/programs/example-native-token-transfers/src/instructions/initialize.rs
- solana/programs/example-native-token-transfers/src/instructions/release_inbound.rs
- solana/programs/example-native-token-transfers/src/lib.rs
- solana/programs/example-native-token-transfers/src/queue/inbox.rs
- solana/programs/example-native-token-transfers/tests/common/setup.rs
- solana/programs/example-native-token-transfers/tests/sdk/instructions/initialize.rs
- solana/tests/anchor.test.ts
- solana/ts/idl/3_0_0/json/example_native_token_transfers.json
- solana/ts/idl/3_0_0/ts/example_native_token_transfers.ts
- solana/ts/lib/ntt.ts
- solana/ts/sdk/ntt.ts
This PR adds:
* Remove `initialize_multisig` and `release_inbound_mint_multisig` ix
* Add `Option<'info, SplMultisig<'info>>` account to `Initialize` and `ReleaseInboundMint` struct
* Update cargo and TS tests
* Derive multisig token authority from the token mint authority
* Update IDL
> solana: Remove `*_multisig` instruction variants

- solana/programs/example-native-token-transfers/src/instructions/admin/mod.rs
Currently when peer is upgraded, the rate limit is reset.
This PR sets rate limit to new rate limit if the rate limit is uninitialized/unused. Otherwise it updates the rate limit.
> solana: Fix rate limit reset on peer upgrade

- cli/test/sepolia-bsc.sh
- evm/script/ConfigureWormholeNtt.s.sol
- evm/script/DeployWormholeNtt.s.sol
- evm/script/helpers/DeployWormholeNttBase.sol
- evm/ts/src/ntt.ts
- sdk/__tests__/index.test.ts
- sdk/__tests__/utils.ts
* Set a `messageFee` > 0 for NTT SDK e2e tests  (Tilt)
* Set a `messageFee` > 0 for NTT cli tests
* Fixed a couple of issues regarding `wormholeTransceiver.initialize` and `wormholeTransceiver.setWormholePeer`, both functions are sending a message via core bridge and in some cases `messageFee` was not taken into account
> Tests and fixes when core bridge messageFee is > 0

- solana/programs/example-native-token-transfers/src/instructions/admin/mod.rs
- solana/programs/example-native-token-transfers/src/instructions/luts.rs
- solana/ts/idl/3_0_0/json/example_native_token_transfers.json
- solana/ts/idl/3_0_0/ts/example_native_token_transfers.ts
- solana/ts/lib/ntt.ts
- solana/ts/sdk/ntt.ts
Since `initialize_lut` instruction is permissionless, an attacker could theoretically backrun the lookup table with garbage values for `sequence` and `fee_collector` accounts as they are unconstrained in this call and are only verified by the core bridge. This could cause transactions that depend on the LUT being initialized correctly to fail due to size constraints. This PR makes `initialize_lut` permissioned using the `owner`.
> solana: Make `initialize_lut` instruction permissioned by `owner`

- solana/programs/example-native-token-transfers/src/instructions/admin/transfer_ownership.rs
This PR adds a check to ensure current owner is not `upgrade_lock` and only then performs the CPI call to `set_upgrade_authority_checked`.
> solana: Skip upgrade authority CPI if current owner is `upgrade_lock`

- solana/modules/ntt-messages/src/transceiver.rs
- solana/modules/ntt-messages/src/transceivers/wormhole.rs
Compared to the actual size written, `written_size` omits:
* `recipient_ntt_manager.len()` and `(2 + transceiver_payload.len())` for `TransceiverMessage
* 4 bytes for the PREFIX for `WormholeTransceiverInfo` and `WormholeTransceiverRegistration`
This PR fixes that by accounting for the omitted lengths.
> solana: Have `written_size` match actual size written for `TransceiverMessage`, `WormholeTransceiverInfo`, and `WormholeTransceiverRegistration`

- solana/programs/example-native-token-transfers/src/instructions/admin/mod.rs
- solana/programs/example-native-token-transfers/tests/sdk/instructions/admin.rs
- solana/ts/idl/3_0_0/json/example_native_token_transfers.json
- solana/ts/idl/3_0_0/ts/example_native_token_transfers.ts
- solana/ts/sdk/ntt.ts
The `transceiver` account is not required in the `deregister_transceiver` instruction - it could be replaced using `registered_transceiver.transceiver_address` to generate the seed. 
This PR removes the unused account and updates the Rust test, TS SDK helper, and IDL as a result.
> solana: Remove unused `transceiver` account in `DeregisterTransceiver` struct

- solana/programs/example-native-token-transfers/src/instructions/admin/mod.rs
This PR adds constraint to ensure `SetPeerArgs.chain_id != config.chain_id`
> solana: Ensure `SetPeerArgs.chain_id != config.chain_id` in `set_peer`

- cli/install.sh
- cli/src/index.ts
- evm/ts/package.json
- sdk/definitions/package.json
- sdk/route/package.json
- solana/package.json
This PR replace GitHub links pointing to the old repo name (`../wormhole-foundation/example-native-token-transfers`) with ones pointing to the new repo name (`../wormhole-foundation/native-token-transfers`) for the `cli`, `solana`, `evm`, and `sdk` directory files and packages.
> chore: Update GitHub repo links pointing to old repo name

- solana/ts/sdk/nttWithExecutor.ts
We need to pass in the correct token program when fetching the ATA.
> solana/ts/sdk: token 2022 get ATA fix

- solana/Anchor.toml
This feature is not enabled on mainnet. Thus, we deactivate it to ensure stack and heap limits are as expected.
> solana: Deactivate direct mapping feature for testing to detect stack frame issues

- cli/package.json
- cli/src/diff.ts
- cli/src/evmsigner.ts
- cli/src/getSigner.ts
- cli/src/index.ts
- cli/src/types.d.ts
- cli/test/sepolia-bsc.sh
- package.json
This makes it so the EVM deployments don't enable standard/special relaying on the WH transceiver when the executor flag is set to true in the config.
> cli: add executor support

- cli/src/index.ts
This vastly improves the error message when the wrong solana-cli version is installed. Before this change, it just prints a cryptic file not found error.
Also changed the `checkAnchorVersion` function to read the expected version from the Anchor.toml of the relevant worktree. This makes the function robust in the future in case future ntt versions are upgraded to newer anchor versions.
> cli: check solana-cli version

- Tiltfile
- solana/.gitignore
- solana/Dockerfile
- solana/Makefile
- solana/README.md
This PR was initially based on https://github.com/wormhole-foundation/native-token-transfers/pull/403. However, due to reasons mentioned in [this comment](https://github.com/wormhole-foundation/native-token-transfers/pull/646#issuecomment-3014103037), the Dockerfile changes were reverted.
tl;dr: 
This PR adds:
* Add `artifacts-mainnet`, `artifacts-solana-devnet`, and `artifacts-tilt-devnet` Makefile target to generate verifiable build artifacts using `solana-verify build`
* Remove `prod-build` Makefile target
> solana: Deterministic builds via Docker

- cli/src/index.ts
From @kcsongor in commit e43c778
"cli: set wormhole address in solana binary by patching it
The problem: solana binaries contain program addresses embedded into
them. Specifically, NTT includes the address of the Wormhole program
it's linked against. Which Wormhole address to include is controlled via
feature flags in the wormhole-anchor-sdk crate, which supports one of
mainnet, devnet, and localhost. For other SVM chains, like Fogo, we
can't build this binary correctly, because there is no way to tell it
which core address to use.
One solution is to roll out an updated version of the
wormhole-anchor-sdk, which allows setting the Wormhole address via an
environment variable. That is likely the prudent solution, but it will
need to be backported to older NTT versions (in case a Fogo …
> set wormhole address in solana binary by patching it, to enable other SVM chains to work with the CLI

- cli/src/index.ts
Example:
❯ ntt transfer-ownership Unichain --destination DESTIONATION_WALLET --path deployment.json
```
Transferring ownership on Unichain (Mainnet)
Manager address: NTT_MANAGER
New owner: DESTIONATION_WALLET
Current owner: CURRENT_OWNER_WALLET
Are you sure you want to move the ownership over the NTT contracts over to DESTIONATION_WALLET? [y/n]y
Transaction hash: 0xe3548
Waiting for 1 confirmation...
Verifying ownership transfer...
✅ Ownership transferred successfully to DESTIONATION_WALLET
```
> add transfer ownership functionality for evm to the CLI

- evm/test/NttManager.t.sol
- evm/test/NttManagerNoRateLimiting.t.sol
This test started failing as of forge v1.3.1, specifically due to this PR https://github.com/foundry-rs/foundry/pull/10446.
The PR implements better error reporting *when the tests run in verbose mode*, so the test that previously expected an empty revert string now fails in verbose mode, because forge now returns an error about calling a contract with no bytecode.
Actually this test was supposed to test (according to the comment) that the transceiver constructor revert if the manager doesn't have the token method, but that's not what it was testing. So we change the test to actually use a dummy contract that has no token method. This returns an empty revert string, so everything is good. Until forge includes an override for that too at least
> evm: fix test_transceiverIncompatibleNttManager

- sui/ts/src/nttWithExecutor.ts
This was a regression during sui/implementation PR review.
> fix: Executor *transfer function should yield instead of return

- sui/ts/__tests__/nttWithExecutor.test.ts
- sui/ts/src/nttWithExecutor.ts
> Fix splitCoins call for non-native tokens

- sui/ts/src/bcs-types.ts
- sui/ts/src/ntt.ts
- sui/ts/src/utils.ts
This will replace the previous logic to retrieve inbox item where we iterate through all dynamic fields in the manager contract. Instead we will call the onchain function borrow_inbox_item to get a reference to the inbox item and parse that to be used in tracking the transaction.
> Use borrow_inbox_item to retrieve inbox item

- cli/src/index.ts
- evm/ts/package.json
- package-lock.json
- package.json
- sdk/definitions/package.json
- sdk/examples/package.json
- sdk/route/package.json
- solana/package.json
- sui/ts/package.json
This PR adds support for XRPL EVM to the CLI 🙂 
steps I did
```bash
npm ci
npm install @wormhole-foundation/sdk@2.5.0
cd sdk/examples
npm install @wormhole-foundation/sdk@2.5.0
cd ../../evm/ts 
npm r @wormhole-foundation/sdk-base @wormhole-foundation/sdk-definitions
cd ../../solana
npm r @wormhole-foundation/sdk-base @wormhole-foundation/sdk-definitions
cd ../sui/ts
npm r @wormhole-foundation/sdk-base @wormhole-foundation/sdk-definitions
cd ../../sdk/definitions
npm i --save-peer @wormhole-foundation/sdk-base@2.5.0 @wormhole-foundation/sdk-definitions@2.5.0
cd ../../evm/ts
npm i --save-peer @wormhole-foundation/sdk-base@2.5.0 @wormhole-foundation/sdk-definitions@2.5.0 @wormhole-foundation/sdk-evm@2.5.0 @wormhole-foundation/sdk-evm-core@2.5.0
cd ../../solana
npm i --save-peer …
```
> ts sdk: 2.5.0 version bump
