wormhole-foundation/native-token-transfers

src/EndpointManager.sol, src/interfaces/IEndpointManager.sol, src/libraries/EndpointStructs.sol, test/EndpointManager.t.sol
This PR cleans up the schema a little bit. The commits are best reviewed separately.
=> Schema cleanup

src/EndpointAndManager.sol, src/EndpointManager.sol, src/EndpointManagerStandalone.sol, src/EndpointRegistry.sol, src/interfaces/IEndpointManager.sol, src/interfaces/IEndpointManagerStandalone.sol, src/libraries/external/ReentrancyGuardUpgradeable.sol, test/EndpointManager.t.sol
The main purpose of this PR is to use deterministic storage slots everywhere in `EndpointManager`, but it includes some bug fixes and refactoring too.
=> EndpointManager: custom storage slots

src/EndpointAndManager.sol, src/EndpointManager.sol, src/EndpointManagerStandalone.sol, src/WormholeEndpointAndManager.sol, src/interfaces/IEndpointManager.sol, test/EndpointManager.t.sol
Partially addresses https://github.com/wormhole-foundation/example-native-token-transfers/issues/15
=> EndpointManager: Add global outbound rate limits

src/EndpointManager.sol, src/interfaces/IEndpointManager.sol, test/EndpointManager.t.sol
https://github.com/wormhole-foundation/example-native-token-transfers/issues/15
=> EndpointManager: add outbound transfers queue

src/EndpointManager.sol, src/interfaces/IEndpointManager.sol, src/interfaces/IEndpointManagerEvents.sol, test/EndpointManager.t.sol
https://github.com/wormhole-foundation/example-native-token-transfers/issues/14
=> EndpointManager: add inbound rate limiting logic with queue

foundry.toml, src/Manager.sol, src/libraries/EndpointStructs.sol, test/Manager.t.sol
https://github.com/wormhole-foundation/example-native-token-transfers/issues/12
=> Add msg.sender to wire format

src/Endpoint.sol, src/EndpointAndManager.sol, src/EndpointStandalone.sol, src/Manager.sol, src/ManagerStandalone.sol, src/WormholeEndpoint.sol, src/WormholeEndpointAndManager.sol, src/interfaces/IEndpoint.sol, src/interfaces/IEndpointStandalone.sol, src/interfaces/IManager.sol, test/Manager.t.sol
- Remove receiver interfaces from Endpoint
- Remove sibling interfaces -- these are Endpoint specific
=> Interface cleanup

src/EndpointAndManager.sol, src/Manager.sol, src/ManagerStandalone.sol, src/interfaces/IManager.sol, test/Manager.t.sol
Changes:
- revert if dust amount included
- refactor to make outbound rate limiting clearer
https://github.com/wormhole-foundation/example-native-token-transfers/issues/6
=> Rate Limiting Refactor

src/Manager.sol, src/WormholeEndpoint.sol, src/WormholeEndpointAndManager.sol, src/interfaces/IManager.sol, src/libraries/EndpointStructs.sol, test/Manager.t.sol
https://github.com/wormhole-foundation/example-native-token-transfers/issues/22
=> Add sibling registration and validation to manager contract

src/Manager.sol, src/interfaces/IManager.sol, src/libraries/EndpointStructs.sol, test/Manager.t.sol
https://github.com/wormhole-foundation/example-native-token-transfers/issues/25
=> Remove ManagerMessage.msgType

src/Manager.sol, src/libraries/EndpointStructs.sol, test/Manager.t.sol
Closes https://github.com/wormhole-foundation/example-native-token-transfers/issues/35
Closes https://github.com/wormhole-foundation/example-native-token-transfers/issues/39
=> Add Prefix and source token address to NativeTokenTransfer struct

src/Endpoint.sol, src/WormholeEndpoint.sol, src/libraries/EndpointStructs.sol, test/Manager.t.sol
=> fix: wrap Manager msg in Endpoint msg

src/Manager.sol, src/ManagerStandalone.sol, src/WormholeEndpoint.sol, src/interfaces/IManagerEvents.sol
=> emit events to notify clients

foundry.toml, src/Manager.sol
Closes https://github.com/wormhole-foundation/example-native-token-transfers/issues/29
=> Disable --via-ir and block scope variables

src/Manager.sol, src/interfaces/IManager.sol
=> manager: change timestamps from u256 to u64

src/Manager.sol, src/interfaces/IManager.sol, src/interfaces/IManagerEvents.sol, src/interfaces/IRateLimiter.sol, src/interfaces/IRateLimiterEvents.sol, src/libraries/RateLimiter.sol, test/Manager.t.sol
Closes https://github.com/wormhole-foundation/example-native-token-transfers/issues/51
=> Pull out rate limiting logic into abstract contract

.gitignore, src/Endpoint.sol, src/EndpointAndManager.sol, src/EndpointRegistry.sol, src/EndpointStandalone.sol, src/Manager.sol, src/ManagerStandalone.sol, src/WormholeEndpoint.sol, src/WormholeEndpointAndManager.sol, src/WormholeEndpointStandalone.sol, src/interfaces/IEndpointStandalone.sol, src/interfaces/IEndpointToken.sol, src/interfaces/IManager.sol, src/interfaces/IManagerEvents.sol, src/interfaces/IManagerStandalone.sol, src/interfaces/IRateLimiter.sol, src/interfaces/IRateLimiterEvents.sol, src/interfaces/IWormholeEndpoint.sol, src/libraries/EndpointHelpers.sol, src/libraries/EndpointStructs.sol, src/libraries/Implementation.sol, src/libraries/NormalizedAmount.sol, src/libraries/RateLimiter.sol, src/wormhole/Governance.sol, test/Manager.t.sol, test/libraries/Implementation.t.sol, test/libraries/Utils.sol, test/wormhole/Governance.t.sol
The commits are best reviewed separately (and should be rebased instead of squashed)
=> NormalizedAmount value type

src/Manager.sol, src/interfaces/IManager.sol, src/interfaces/IManagerEvents.sol, src/libraries/EndpointStructs.sol, test/Manager.t.sol
Closes https://github.com/wormhole-foundation/example-native-token-transfers/issues/56
=> Use bytes32 for addresses instead of bytes memory

src/Manager.sol
=> Manager: refund using [`call`] instead of [`transfer`]

src/WormholeEndpoint.sol
=> WormholeEndpoint: parse Endpoint Message first in relayer flow

src/WormholeEndpoint.sol
=> WormholeEndpoint: revert on checkInvalidRelayingConfig elsewhere

src/Manager.sol, test/Manager.t.sol
=> Manager: normalize after locking/burning

src/WormholeEndpoint.sol
=> WormholeEndpoint: check EndpointMessage is consumed on parsing

src/Manager.sol, src/interfaces/IRateLimiter.sol, src/libraries/RateLimiter.sol
=> Fix: modify _transfer to use original msg.sender

src/Manager.sol, src/interfaces/IManager.sol, src/interfaces/IManagerEvents.sol, test/Manager.t.sol
=> Manager: end execution early on replay protection

foundry.toml, src/Manager.sol, src/interfaces/IRateLimiter.sol, src/libraries/EndpointStructs.sol, src/libraries/NormalizedAmount.sol, src/libraries/RateLimiter.sol, test/Manager.t.sol, test/NormalizedAmount.t.sol
=> Normalize amounts correctly based on number of decimals

src/Endpoint.sol, src/EndpointAndManager.sol, src/EndpointStandalone.sol, src/Manager.sol, src/ManagerStandalone.sol, src/WormholeEndpoint.sol, src/interfaces/IEndpointStandalone.sol, src/interfaces/IManager.sol, src/interfaces/IRateLimiter.sol, src/libraries/EndpointStructs.sol, src/libraries/RateLimiter.sol, test/Manager.t.sol, test/RateLimit.t.sol, test/mocks/DummyEndpoint.sol
Add EndpointInstructions struct and enable sending without relaying via WormholeEndpointInstructions
=> Add EndpointInstructions struct

src/WormholeEndpoint.sol
=> Remove pausing functionality on receive Message

src/EndpointStandalone.sol, src/ManagerStandalone.sol, test/IntegrationRelayer.t.sol, test/IntegrationStandalone.t.sol, test/Upgrades.t.sol, test/mocks/DummyToken.sol
* Standalone with a single endpoint and multiple endpoints
* Standalone while using the relayer
* Upgrade tests to ensure invariant checking and migration works as expected
=> End to end tests for wormhole integration

src/Endpoint.sol, src/EndpointAndManager.sol, src/EndpointStandalone.sol, src/WormholeEndpoint.sol, src/WormholeEndpointAndManager.sol, src/WormholeEndpointStandalone.sol, src/interfaces/ISpecialRelayer.sol, src/interfaces/IWormholeEndpoint.sol, src/libraries/EndpointHelpers.sol, test/IntegrationRelayer.t.sol, test/IntegrationStandalone.t.sol, test/Manager.t.sol, test/Upgrades.t.sol, test/mocks/DummyEndpoint.sol
Add special relayer quoting logic to handle specialized target chain deliveries
=> Add WormholeEndpoint Special Relayer

evm/src/Manager.sol, evm/test/Upgrades.t.sol
=> fix: cache the deployer to mitigate front-running on initialization

evm/src/wormhole/Governance.sol, evm/test/wormhole/Governance.t.sol
Re-opening https://github.com/wormhole-foundation/example-native-token-transfers/pull/146
=> evm: cleanup: remove module from governance struct

.github/workflows/test.yml, evm/src/WormholeEndpoint.sol, evm/test/IntegrationRelayer.t.sol, evm/test/IntegrationStandalone.t.sol, evm/test/Upgrades.t.sol, evm/test/mocks/MockEndpoints.sol
=> feat: add configurable consistency level

evm/src/WormholeEndpoint.sol
=> WormholeEndpoint: remove abstract

evm/src/Manager.sol, evm/src/interfaces/IManagerEvents.sol
=> Manager: emit event after a transfer is redeemed

evm/src/Endpoint.sol, evm/src/Manager.sol, evm/src/NttNormalizer.sol, evm/src/WormholeEndpoint.sol, evm/src/interfaces/IManager.sol, evm/src/interfaces/IWormholeEndpoint.sol, evm/src/libraries/EndpointStructs.sol, evm/src/libraries/RateLimiter.sol, evm/test/IntegrationRelayer.t.sol
1. Do the messages we're emitting contain all the information we need?
2. Does the payload format with the new prefixes make sense, or would another format be preferable?
=> evm: Wormhole endpoint registration

.github/workflows/sdk.yml
this way the diff will pick up redundant files
=> CI: remove evm_binding before regenerating it

evm/src/Transceiver/WormholeTransceiver/WormholeTransceiver.sol, evm/src/Transceiver/WormholeTransceiver/WormholeTransceiverState.sol, evm/test/IntegrationRelayer.t.sol, evm/test/IntegrationStandalone.t.sol, evm/test/Upgrades.t.sol, evm/test/mocks/MockTransceivers.sol
=> fix: gas limit constant -> immutable

README.md, evm/src/NttManager/NttManager.sol, evm/src/NttManager/NttManagerState.sol, evm/src/interfaces/INttManagerEvents.sol, evm/src/interfaces/INttManagerState.sol, evm/src/libraries/TrimmedAmount.sol, evm/test/IntegrationRelayer.t.sol, evm/test/IntegrationStandalone.t.sol, evm/test/NttManager.t.sol, evm/test/RateLimit.t.sol, evm/test/TrimmedAmount.t.sol, evm/test/Upgrades.t.sol, evm/test/libraries/NttManagerHelpers.sol, solana/modules/ntt-messages/src/trimmed_amount.rs, solana/programs/example-native-token-transfers/src/instructions/admin.rs, solana/programs/example-native-token-transfers/src/instructions/transfer.rs, solana/programs/example-native-token-transfers/src/peer.rs, solana/programs/example-native-token-transfers/tests/common/setup.rs, solana/programs/example-native-token-transfers/tests/transfer.rs, solana/tests/example-native-token-transfer.ts, solana/ts/sdk/index.ts
=> cap decimal trimming by destination decimals

evm/src/NttManager/NttManager.sol
We might refund some native token so the event should actually only emit the total quote paid
=> evm: Fix transfer event

solana/modules/ntt-messages/src/lib.rs, solana/modules/ntt-messages/src/mode.rs, solana/modules/ntt-messages/src/transceivers/wormhole.rs, solana/programs/example-native-token-transfers/src/config.rs, solana/programs/example-native-token-transfers/src/instructions/initialize.rs, solana/programs/example-native-token-transfers/src/instructions/release_inbound.rs, solana/programs/example-native-token-transfers/src/instructions/transfer.rs, solana/programs/example-native-token-transfers/src/lib.rs, solana/programs/example-native-token-transfers/src/transceivers/wormhole/accounts.rs, solana/programs/example-native-token-transfers/src/transceivers/wormhole/instructions/broadcast_id.rs, solana/programs/example-native-token-transfers/src/transceivers/wormhole/instructions/broadcast_peer.rs, solana/programs/example-native-token-transfers/src/transceivers/wormhole/instructions/mod.rs, solana/programs/example-native-token-transfers/src/transceivers/wormhole/instructions/release_outbound.rs, solana/programs/example-native-token-transfers/src/transceivers/wormhole/mod.rs, solana/programs/example-native-token-transfers/tests/broadcast.rs, solana/programs/example-native-token-transfers/tests/cancel_flow.rs, solana/programs/example-native-token-transfers/tests/common/setup.rs, solana/programs/example-native-token-transfers/tests/governance.rs, solana/programs/example-native-token-transfers/tests/sdk/instructions/transfer.rs, solana/programs/example-native-token-transfers/tests/sdk/transceivers/wormhole/accounts/mod.rs, solana/programs/example-native-token-transfers/tests/sdk/transceivers/wormhole/accounts/wormhole.rs, solana/programs/example-native-token-transfers/tests/sdk/transceivers/wormhole/instructions/broadcast_id.rs, solana/programs/example-native-token-transfers/tests/sdk/transceivers/wormhole/instructions/broadcast_peer.rs, solana/programs/example-native-token-transfers/tests/sdk/transceivers/wormhole/instructions/mod.rs, solana/programs/example-native-token-transfers/tests/sdk/transceivers/wormhole/instructions/release_outbound.rs, solana/programs/example-native-token-transfers/tests/sdk/transceivers/wormhole/mod.rs, solana/programs/example-native-token-transfers/tests/transfer.rs, solana/ts/sdk/index.ts
=> solana: send message about transceiver info + registration info

evm/src/libraries/RateLimiter.sol, evm/src/libraries/TrimmedAmount.sol
This is a prime target for upcoming fuzz testing so I'm not shoehorning a test in with this change
=> evm: Fix possible overflow on backfilling

evm/src/libraries/PausableUpgradeable.sol
=> fix: remove unused error

evm/src/Transceiver/WormholeTransceiver/WormholeTransceiverState.sol, evm/src/interfaces/IWormholeTransceiverState.sol, evm/test/IntegrationRelayer.t.sol
=> fix: modify [`setIsWormholeEvmChain`] to take bool

evm/test/IntegrationRelayer.t.sol, evm/test/IntegrationStandalone.t.sol, evm/test/NttManager.t.sol, evm/test/TransceiverStructs.t.sol, evm/test/TrimmedAmount.t.sol, evm/test/Upgrades.t.sol
=> evm: add revert signatures

evm/src/Transceiver/WormholeTransceiver/WormholeTransceiverState.sol, evm/src/libraries/BooleanFlag.sol, evm/src/libraries/TransceiverHelpers.sol
=> evm: use user-defined type for boolean flag

evm/test/IntegrationStandalone.t.sol, evm/test/NttManager.t.sol, evm/test/RateLimit.t.sol, evm/test/Upgrades.t.sol, evm/test/wormhole/Governance.t.sol
The purpose of this PR is to fix the CI tests by swapping goerli out for sepolia in the evm tests.
=> evm: swap goerli fork for sepolia

solana/programs/example-native-token-transfers/src/transceivers/wormhole/instructions/broadcast_id.rs, solana/programs/example-native-token-transfers/src/transceivers/wormhole/instructions/broadcast_peer.rs, solana/programs/example-native-token-transfers/src/transceivers/wormhole/instructions/release_outbound.rs
Remove `mut` from emitter account.
=> solana: remove mut

solana/programs/example-native-token-transfers/src/transceivers/wormhole/instructions/receive_message.rs, solana/programs/example-native-token-transfers/tests/sdk/transceivers/wormhole/instructions/receive_message.rs, solana/ts/sdk/ntt.ts
=> solana: Add pausing to Receive entrypoint

solana/programs/example-native-token-transfers/src/error.rs, solana/programs/example-native-token-transfers/src/instructions/redeem.rs
Resolves: https://github.com/wormhole-foundation/example-native-token-transfers/issues/323
=> solana: Prevent redeem if threshold is zero

solana/programs/ntt-quoter/src/error.rs, solana/programs/ntt-quoter/src/lib.rs, solana/programs/ntt-quoter/src/processor/admin.rs, solana/programs/ntt-quoter/src/processor/request_relay.rs, solana/programs/ntt-quoter/src/state.rs, solana/ts/sdk/quoter.ts
* assumes evm gas cost is the same across all chains
* very egalitarian - does not allow for subsidizing costs
=> solana: support for multiple ntt tokens with the same quoter

evm/src/NttManager/NttManager.sol, evm/src/interfaces/INttManager.sol, evm/src/libraries/TransceiverStructs.sol, evm/test/NttManager.t.sol
=> evm: Revert properly when index out of bounds and cancelling queued outbound transfers

solana/programs/example-native-token-transfers/src/instructions/initialize.rs, solana/programs/example-native-token-transfers/src/instructions/redeem.rs, solana/programs/example-native-token-transfers/src/queue/inbox.rs
Resolves: https://github.com/wormhole-foundation/example-native-token-transfers/issues/343
=> solana: Add init_if_needed for ATA in initialize

ci_tests/src/index.ts, evm/src/NttManager/ManagerBase.sol, evm/src/NttManager/NttManager.sol, evm/src/Transceiver/Transceiver.sol, evm/src/Transceiver/WormholeTransceiver/WormholeTransceiver.sol, evm/src/interfaces/INttManager.sol, evm/src/interfaces/IRateLimiter.sol, evm/src/interfaces/ITransceiver.sol, evm/src/interfaces/IWormholeTransceiverState.sol, evm/src/libraries/RateLimiter.sol, evm/test/IntegrationManual.t.sol, evm/test/IntegrationRelayer.t.sol, evm/test/IntegrationStandalone.t.sol, evm/test/NttManager.t.sol, evm/test/RateLimit.t.sol, evm/test/Upgrades.t.sol, evm/test/libraries/IntegrationHelpers.sol, evm/test/mocks/DummyTransceiver.sol
=> evm: add support for refund address for standard relaying

evm/env/.env.sample
=> Change default finality to `202` (finalized)

.github/workflows/tilt.yml, Tiltfile, ci_tests/.dockerignore, ci_tests/.gitignore, ci_tests/package-lock.json, ci_tests/package.json, ci_tests/src/accountant.ts, ci_tests/src/index.ts, solana/package-lock.json, solana/package.json, solana/tests/example-native-token-transfer.ts, solana/ts/sdk/ntt.ts, solana/ts/sdk/nttLayout.ts
Rebasing branch to see if it still passes CI
=> e2e: add accountant

solana/programs/example-native-token-transfers/src/bitmap.rs, solana/programs/example-native-token-transfers/src/config.rs, solana/programs/example-native-token-transfers/src/error.rs, solana/programs/example-native-token-transfers/src/instructions/admin.rs, solana/programs/example-native-token-transfers/src/instructions/redeem.rs, solana/programs/example-native-token-transfers/src/queue/outbox.rs, solana/programs/example-native-token-transfers/src/transceivers/wormhole/instructions/release_outbound.rs, solana/programs/example-native-token-transfers/tests/transfer.rs, solana/programs/ntt-quoter/src/processor/request_relay.rs
=> solana: Add error handling for Bitmap indexing

.github/workflows/tilt.yml, sdk/Dockerfile, sdk/__tests__/utils.ts, sdk/definitions/src/ntt.ts, sdk/evm/__tests__/versions.test.ts, sdk/evm/package.json, sdk/evm/scripts/readVersion.ts, sdk/evm/src/ntt.ts, sdk/package-lock.json, sdk/package.json, sdk/solana/.gitignore, sdk/solana/__tests__/ntt.test.ts, sdk/solana/jest.config.ts, sdk/solana/package.json, sdk/solana/scripts/readVersion.ts, sdk/solana/src/anchor-idl/1_0_0.ts, sdk/solana/src/anchor-idl/1_0_0/example_native_token_transfers.json, sdk/solana/src/anchor-idl/1_0_0/example_native_token_transfers.ts, sdk/solana/src/anchor-idl/1_0_0/ntt_quoter.json, sdk/solana/src/anchor-idl/1_0_0/ntt_quoter.ts, sdk/solana/src/anchor-idl/1_0_0/wormhole_governance.json, sdk/solana/src/anchor-idl/1_0_0/wormhole_governance.ts, sdk/solana/src/anchor-idl/index.ts, sdk/solana/src/bindings.ts, sdk/solana/src/ntt.ts, sdk/solana/src/utils.ts, sdk/solana/tsconfig.cjs.json, sdk/solana/tsconfig.esm.json, solana/Makefile
- Add a method to fetch the version of in the contract source file to set the directory for generated bindings
- Add implementation of version fetching from on-chain program for Solana 
- Add version indirection to select bindings at runtime
- Add versioned IDL to git tracking
=> SDK: Solana Versioning

.github/workflows/evm.yml, .gitmodules, Makefile, evm/echidna.yaml, evm/echidna/FuzzNttManager.sol, evm/echidna/FuzzWormholeTransceiver.sol, evm/echidna/helpers/FuzzingHelpers.sol, evm/echidna/helpers/IHevm.sol
This PR adds echidna stateful fuzzing for the manager and performs a fuzzing run as part of the CI pipeline now.
The fuzzing suite only touches the manager due to time constraints.
=> evm: Echidna stateful fuzzing for NttManager

.github/workflows/sdk.yml, evm/ts/src/ntt.ts, sdk/route/__tests__/route.test.ts, sdk/route/src/automatic.ts
The publish job failed because tests were failing when it ran the `npm run test` command which I never ran locally. These test should run when a PR is opened
=> Added additional SDK tests to CI job

.github/workflows/solana.yml, evm/script/helpers/ParseNttConfig.sol, evm/src/NttManager/NttManager.sol, evm/src/Transceiver/WormholeTransceiver/WormholeTransceiver.sol, evm/src/interfaces/INttManager.sol, evm/src/interfaces/IRateLimiter.sol, evm/src/interfaces/IWormholeTransceiver.sol, evm/src/libraries/RateLimiter.sol, evm/src/libraries/TransceiverStructs.sol, evm/src/wormhole/Governance.sol, evm/test/TransceiverStructs.t.sol, evm/test/libraries/IntegrationHelpers.sol, evm/test/libraries/TransceiverHelpers.sol, evm/test/libraries/Utils.sol, evm/test/mocks/DummyTransceiver.sol
* **EVM**: forge formatter changed preferences which caused previous code to fail `make check-format` (`forge fmt --check`). Updated formatting for those files.
* **Solana**: GitHub runner fails with ``error: linking with `cc` failed: exit status: 1`` and the raw logs show a disk space warning. Switched to a dedicated (`tilt-kube-public`) runner for the `Solana Cargo SBF` job to make use of better CPU and cache than GitHub runner.
=> CI: Fix EVM and Solana Cargo SBF CI

cli/README.md, cli/src/index.ts
Now that it's available.
Also update the README
=> cli: update install script URL to main branch

cli/package.json, evm/ts/package.json, package-lock.json, package.json, sdk/definitions/package.json, sdk/examples/package.json, sdk/route/package.json, solana/package.json
Needed for additional payload support https://github.com/wormhole-foundation/example-native-token-transfers/pull/522
=> ts sdk: 0.3.0 version bump

evm/src/interfaces/INttManager.sol
This PR adds `indexed` to `recipient` and `refundAddress` fields of `TransferSent` event
=> evm: Add indexing in TransferSent event

solana/ts/scripts/config/mainnet/quoter.json, solana/ts/scripts/registerManagers.ts
This includes quoter typo fixes, AVAX and BLAST entries plus  small sleep to avoid rate-limit during updates.
NOTE:
This must supersede #602; it must be closed after this one is  merged.
=> AVAX/BLAST NTT entries + typo fixes

solana/Cargo.toml, solana/programs/example-native-token-transfers/src/instructions/admin/transfer_ownership.rs, solana/programs/example-native-token-transfers/src/instructions/release_inbound.rs, solana/programs/example-native-token-transfers/src/instructions/transfer.rs, solana/programs/example-native-token-transfers/src/queue/outbox.rs, solana/programs/example-native-token-transfers/src/transceivers/wormhole/accounts.rs, solana/programs/example-native-token-transfers/src/transceivers/wormhole/instructions/broadcast_id.rs, solana/programs/example-native-token-transfers/src/transceivers/wormhole/instructions/broadcast_peer.rs, solana/programs/ntt-transceiver/src/wormhole/accounts.rs, solana/programs/ntt-transceiver/src/wormhole/instructions/broadcast_id.rs, solana/programs/ntt-transceiver/src/wormhole/instructions/broadcast_peer.rs, solana/programs/wormhole-governance/src/instructions/governance.rs, solana/ts/idl/3_0_0/json/example_native_token_transfers.json, solana/ts/idl/3_0_0/json/ntt_transceiver.json, solana/ts/idl/3_0_0/ts/example_native_token_transfers.ts, solana/ts/idl/3_0_0/ts/ntt_transceiver.ts
=> solana: Add function comments and document some Anchor constraints

sdk/route/src/executor/executor.ts
It's useful to override the gasLimit set by the executor for certain tokens that might use more gas when redeeming.
=> ts/sdk: executor per token gas limit overrides

sdk/route/src/automatic.ts, sdk/route/src/executor/consts.ts, sdk/route/src/executor/executor.ts, sdk/route/src/manual.ts
There are more than 1 SVM platforms now (Fogo)
=> sdk: svm platform check

solana/programs/example-native-token-transfers/tests/admin.rs, solana/programs/example-native-token-transfers/tests/broadcast.rs, solana/programs/example-native-token-transfers/tests/cancel_flow.rs, solana/programs/example-native-token-transfers/tests/common/mod.rs, solana/programs/example-native-token-transfers/tests/common/setup.rs, solana/programs/example-native-token-transfers/tests/common/utils.rs, solana/programs/example-native-token-transfers/tests/governance.rs, solana/programs/example-native-token-transfers/tests/lib.rs, solana/programs/example-native-token-transfers/tests/receive.rs, solana/programs/example-native-token-transfers/tests/sdk/accounts.rs, solana/programs/example-native-token-transfers/tests/sdk/instructions/admin.rs, solana/programs/example-native-token-transfers/tests/sdk/instructions/mod.rs, solana/programs/example-native-token-transfers/tests/sdk/instructions/release_inbound.rs, solana/programs/example-native-token-transfers/tests/sdk/transceivers/wormhole/accounts/wormhole.rs, solana/programs/example-native-token-transfers/tests/sdk/transceivers/wormhole/instructions/release_outbound.rs, solana/programs/example-native-token-transfers/tests/transfer.rs
This PR is based on https://github.com/wormhole-foundation/native-token-transfers/pull/219.
This PR also adds missing Cargo tests mentioned in https://github.com/wormhole-foundation/native-token-transfers/issues/320.
=> solana: Add more Cargo tests

cli/src/index.ts
=> add HyperEVM deployment requirements and slow flag

cli/package.json
bump cli from 1.3.0 on package.json to 1.5.0
=> cli: version update
